#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    sea_level = 0
    valley = 0
    step = 0
    for i in range(0,n):
        if(s[i]=='U'):
            step+=1
        else:
            step-=1
        if(step ==0 and s[i]=='U'):
            valley+=1
    return valley   
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()


